### ISSUE TITLE
Repository not found

### ISSUE THREAD

**Issue by emailsubjekt** [firebase/mlkit-custom-image-classifier#1]
git clone https://github.com/firebase/custom-image-classifier
Repository not found

**Comment by samtstern** [comment]
This is the real link:
https://github.com/firebase/mlkit-custom-image-classifier

Where did you get the bad link?

*From: *emailsubjekt <notifications@github.com>
*Date: *Tue, May 7, 2019, 5:34 PM
*To: *firebase/mlkit-custom-image-classifier
*Cc: *Subscribed

git clone https://github.com/firebase/custom-image-classifier

**Comment by emailsubjekt** [comment]
Thank you. From here https://github.com/firebase/mlkit-custom-image-classifier, from the Getting started section:
"Getting Started
Note: Before proceeding, make sure you have Flutter & Node.js/NPM setup for your system.

Clone this repo locally

git clone https://github.com/firebase/custom-image-classifier "

**Comment by skotwani** [comment]
Thanks for flagging. This has now been fixed.
