### ISSUE TITLE
Socketexception when trying to add new dataset

### ISSUE THREAD

**Issue by kenwen** [firebase/mlkit-custom-image-classifier#9]
Running on device and I'm getting a socketexception when I try to save a new dataset.

Comes up with a failed host lookup message, OS Error: no address associated with hostname, errno = 7

I've checked and the app does have internet access permission

**Comment by prakhar1989** [comment]
Hi, were you able to run through all the steps in [setup](https://github.com/firebase/mlkit-custom-image-classifier#getting-started). More specifically, you'd need to check if your Firebase functions have deployed correctly. 

[This](https://github.com/firebase/mlkit-custom-image-classifier/blob/master/flutter-app/lib/automl_api.dart#L29) is the API the app calls for creating a new dataset, so do confirm if your functions endpoints are deployed and accessible.

**Comment by kenwen** [comment]
Ah, missed out a step in the setup, all sorted

**Comment by eugeneyu** [comment]
@kenwen which step did you miss cuz I'm facing the same issue.

**Comment by kenwen** [comment]
I **_think_** it was the flutter app set up stage, I didn't put the project ID into the file

**Comment by eugeneyu** [comment]
Thanks! Double checked and found i missed the project ID in constants.dart. Added and then resolved.
